from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QFileDialog,
    QGroupBox,
    QHBoxLayout,
    QLabel,
    QListWidget,
    QListWidgetItem,
    QPushButton,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)


class ArtifactPanel(QWidget):
    """
    Artifact browser for generated JSON, trace and KDM files.

    The panel explains what each artifact represents and shows a compact summary
    of its contents when possible.
    """

    ARTIFACT_DESCRIPTIONS = {
        "python_model.json": (
            "Static intermediate model generated by the Python extractor. "
            "It contains files, classes, functions, calls, variables and static relationships."
        ),
        "python_model.runtime_enriched.combined.json": (
            "Static model enriched with dynamic runtime evidence from all executed scenarios."
        ),
        "python_model.runtime_enriched.architecture.json": (
            "Runtime-enriched model after architecture recovery. It contains the recovered StructureModel."
        ),
        "python_model.architecture.json": (
            "Static-only model after architecture recovery. It contains the recovered StructureModel."
        ),
        "python_model.runtime_enriched.ai_architecture.json": (
            "Architecture proposal enriched with pre-review AI suggestions."
        ),
        "python_model.ai_architecture.json": (
            "Static architecture proposal enriched with pre-review AI suggestions."
        ),
        "python_model.reviewed_architecture.json": (
            "Human-reviewed architecture JSON. This is the input used for final KDM generation."
        ),
        "model.reviewed.kdm.xmi": (
            "Final KDM XMI model generated from the reviewed architecture."
        ),
    }

    def __init__(self, parent=None):
        super().__init__(parent)
        self.output_dir = None
        self._build_ui()

    def _build_ui(self):
        layout = QVBoxLayout(self)

        buttons = QHBoxLayout()
        self.select_dir_btn = QPushButton("Select output directory")
        self.refresh_btn = QPushButton("Refresh")
        self.open_file_btn = QPushButton("Open selected")
        self.open_folder_btn = QPushButton("Open folder")
        self.copy_path_btn = QPushButton("Copy path")

        for button in [
            self.select_dir_btn,
            self.refresh_btn,
            self.open_file_btn,
            self.open_folder_btn,
            self.copy_path_btn,
        ]:
            buttons.addWidget(button)

        buttons.addStretch(1)
        layout.addLayout(buttons)

        content = QHBoxLayout()

        left_group = QGroupBox("Generated artifacts")
        left_layout = QVBoxLayout(left_group)
        self.list_widget = QListWidget()
        left_layout.addWidget(self.list_widget)

        right_group = QGroupBox("Artifact details")
        right_layout = QVBoxLayout(right_group)

        self.artifact_title = QLabel("Select an artifact.")
        self.artifact_title.setWordWrap(True)

        self.artifact_description = QLabel("")
        self.artifact_description.setWordWrap(True)

        self.artifact_summary = QTextEdit()
        self.artifact_summary.setReadOnly(True)
        self.artifact_summary.setPlaceholderText(
            "A summary will appear here when an artifact is selected."
        )

        right_layout.addWidget(self.artifact_title)
        right_layout.addWidget(self.artifact_description)
        right_layout.addWidget(self.artifact_summary)

        content.addWidget(left_group, 2)
        content.addWidget(right_group, 3)

        layout.addLayout(content)

        self.select_dir_btn.clicked.connect(self.select_output_dir)
        self.refresh_btn.clicked.connect(self.refresh)
        self.open_file_btn.clicked.connect(self.open_selected)
        self.open_folder_btn.clicked.connect(self.open_folder)
        self.copy_path_btn.clicked.connect(self.copy_selected_path)
        self.list_widget.itemSelectionChanged.connect(self.show_selected_summary)

    def set_output_dir(self, path: str | Path):
        self.output_dir = Path(path)
        self.refresh()

    def select_output_dir(self):
        path = QFileDialog.getExistingDirectory(
            self,
            "Select output directory",
            str(Path.cwd()),
        )

        if path:
            self.set_output_dir(path)

    def refresh(self):
        self.list_widget.clear()

        if not self.output_dir or not self.output_dir.exists():
            self.artifact_title.setText("No output directory selected.")
            self.artifact_description.setText("")
            self.artifact_summary.clear()
            return

        patterns = ["*.json", "*.xmi", "*.xml", "*.txt", "*.log"]
        files = []

        for pattern in patterns:
            files.extend(self.output_dir.glob(pattern))

        for path in sorted(set(files), key=lambda p: self._artifact_sort_key(p)):
            item = QListWidgetItem(path.name)
            item.setData(Qt.ItemDataRole.UserRole, str(path))
            item.setToolTip(str(path))
            self.list_widget.addItem(item)

        if self.list_widget.count() == 0:
            self.artifact_title.setText("No artifacts found.")
            self.artifact_description.setText("")
            self.artifact_summary.clear()

    def show_selected_summary(self):
        item = self.list_widget.currentItem()

        if not item:
            return

        path = Path(item.data(Qt.ItemDataRole.UserRole))
        self.artifact_title.setText(path.name)
        self.artifact_description.setText(self.describe_artifact(path))
        self.artifact_summary.setPlainText(self.summarize_artifact(path))

    def describe_artifact(self, path: Path) -> str:
        name = path.name

        if name in self.ARTIFACT_DESCRIPTIONS:
            return self.ARTIFACT_DESCRIPTIONS[name]

        if name.startswith("runtime_trace.") and name.endswith(".json"):
            scenario = name.removeprefix("runtime_trace.").removesuffix(".json")
            return (
                f"Runtime trace generated for scenario '{scenario}'. "
                "It stores observed calls, returns, exceptions and execution metadata."
            )

        if name.startswith("python_model.runtime_enriched.") and name.endswith(".json"):
            scenario = (
                name.removeprefix("python_model.runtime_enriched.")
                .removesuffix(".json")
            )
            return (
                f"Intermediate model enriched with runtime evidence from scenario '{scenario}'."
            )

        if path.suffix == ".xmi":
            return "KDM or model artifact serialized as XMI."

        if path.suffix == ".json":
            return "JSON artifact generated by the py2kdm pipeline."

        return "Generated artifact."

    def summarize_artifact(self, path: Path) -> str:
        if not path.exists():
            return "File does not exist."

        try:
            if path.suffix == ".json":
                return self._summarize_json(path)

            if path.suffix in {".xmi", ".xml"}:
                return self._summarize_xmi(path)

            return self._summarize_text(path)
        except Exception as exc:
            return f"Could not summarize artifact:\n{exc}"

    def _summarize_json(self, path: Path) -> str:
        with path.open("r", encoding="utf-8") as handle:
            data = json.load(handle)

        lines = []
        lines.append(f"Path: {path}")
        lines.append(f"Size: {path.stat().st_size} bytes")
        lines.append("")

        if isinstance(data, dict):
            lines.append("Top-level keys:")
            for key in sorted(data.keys()):
                value = data.get(key)
                lines.append(f"  - {key}: {self._short_type(value)}")
            lines.append("")

            if "metadata" in data:
                lines.extend(self._summarize_metadata(data.get("metadata", {})))
                lines.append("")

            lines.extend(self._summarize_static_model(data))
            lines.append("")

            lines.extend(self._summarize_runtime(data))
            lines.append("")

            lines.extend(self._summarize_architecture(data))
            lines.append("")

            lines.extend(self._summarize_ai(data))
            lines.append("")

            lines.extend(self._summarize_review(data))

        elif isinstance(data, list):
            lines.append(f"JSON list items: {len(data)}")
        else:
            lines.append(f"JSON value type: {type(data).__name__}")

        return "\n".join(line for line in lines if line is not None)

    def _summarize_metadata(self, metadata: dict) -> list[str]:
        lines = ["Metadata:"]

        if not isinstance(metadata, dict) or not metadata:
            lines.append("  -")
            return lines

        for key in [
            "execution_status",
            "event_count",
            "scenario",
            "mode",
            "execution_error",
        ]:
            if key in metadata:
                value = metadata.get(key)

                if key == "execution_error" and isinstance(value, dict):
                    lines.append(f"  execution_error.type: {value.get('type')}")
                    lines.append(f"  execution_error.message: {value.get('message')}")
                else:
                    lines.append(f"  {key}: {value}")

        return lines

    def _summarize_static_model(self, data: dict) -> list[str]:
        lines = ["Static model:"]

        lines.append(f"  files: {len(data.get('files', []))}")
        lines.append(f"  relationships: {len(data.get('relationships', []))}")

        relationship_counts = {}
        for rel in data.get("relationships", []):
            rel_type = rel.get("type", "unknown")
            relationship_counts[rel_type] = relationship_counts.get(rel_type, 0) + 1

        if relationship_counts:
            lines.append("  relationship types:")
            for rel_type, count in sorted(relationship_counts.items()):
                lines.append(f"    {rel_type}: {count}")

        return lines

    def _summarize_runtime(self, data: dict) -> list[str]:
        lines = ["Runtime enrichment:"]

        runtime = data.get("runtime_enrichment", {})
        summary = runtime.get("summary", {}) if isinstance(runtime, dict) else {}

        if summary:
            for key, value in summary.items():
                lines.append(f"  {key}: {value}")
            return lines

        runtime_calls = [
            rel
            for rel in data.get("relationships", [])
            if isinstance(rel, dict) and rel.get("type") == "runtime_calls"
        ]

        if runtime_calls:
            lines.append(f"  runtime_calls: {len(runtime_calls)}")
            scenarios = sorted(
                {
                    rel.get("scenario")
                    for rel in runtime_calls
                    if rel.get("scenario")
                }
            )
            lines.append(f"  scenarios: {scenarios or '-'}")
        else:
            lines.append("  -")

        return lines

    def _summarize_architecture(self, data: dict) -> list[str]:
        lines = ["Architecture model:"]

        structure_model = data.get("structure_model", {})

        if not isinstance(structure_model, dict) or not structure_model:
            lines.append("  -")
            return lines

        lines.append(f"  subsystems: {len(structure_model.get('subsystems', []))}")
        lines.append(f"  control_loops: {len(structure_model.get('control_loops', []))}")
        lines.append(f"  components: {len(structure_model.get('components', []))}")
        lines.append(
            f"  structure_relationships: "
            f"{len(structure_model.get('structure_relationships', []))}"
        )
        lines.append(
            f"  containment_relationships: "
            f"{len(structure_model.get('containment_relationships', []))}"
        )

        role_counts = {}
        for component in structure_model.get("components", []):
            role = component.get("role", "unknown")
            role_counts[role] = role_counts.get(role, 0) + 1

        if role_counts:
            lines.append("  component roles:")
            for role, count in sorted(role_counts.items()):
                lines.append(f"    {role}: {count}")

        consistency = data.get("architecture_consistency", {})
        if consistency:
            lines.append("  architecture_consistency:")
            lines.append(f"    status: {consistency.get('status', '-')}")
            lines.append(
                f"    warnings: {len(consistency.get('warnings', []))}"
            )
            lines.append(
                f"    blocked_constructions: "
                f"{len(consistency.get('blocked_constructions', []))}"
            )

        return lines

    def _summarize_ai(self, data: dict) -> list[str]:
        lines = ["AI enrichment:"]

        ai = data.get("ai_enrichment", {})

        if not isinstance(ai, dict) or not ai:
            lines.append("  -")
            return lines

        summary = ai.get("summary", {})
        suggestions = ai.get("suggestions", [])

        if summary:
            lines.append("  summary:")
            for key, value in summary.items():
                lines.append(f"    {key}: {value}")

        lines.append(f"  suggestions: {len(suggestions)}")

        status_counts = {}
        for suggestion in suggestions:
            status = suggestion.get("status", "unknown")
            status_counts[status] = status_counts.get(status, 0) + 1

        if status_counts:
            lines.append("  suggestion statuses:")
            for status, count in sorted(status_counts.items()):
                lines.append(f"    {status}: {count}")

        return lines

    def _summarize_review(self, data: dict) -> list[str]:
        lines = ["Human review:"]

        review = data.get("architecture_review", {})

        if not isinstance(review, dict) or not review:
            lines.append("  -")
            return lines

        decisions = review.get("ai_suggestion_decisions", [])
        actions = review.get("actions", [])

        lines.append(f"  ai_suggestion_decisions: {len(decisions)}")
        lines.append(f"  review_actions: {len(actions)}")

        decision_counts = {}
        for decision in decisions:
            value = decision.get("decision", "unknown")
            decision_counts[value] = decision_counts.get(value, 0) + 1

        if decision_counts:
            lines.append("  decision counts:")
            for decision, count in sorted(decision_counts.items()):
                lines.append(f"    {decision}: {count}")

        return lines

    def _summarize_xmi(self, path: Path) -> str:
        text = path.read_text(encoding="utf-8", errors="replace")
        lines = []
        lines.append(f"Path: {path}")
        lines.append(f"Size: {path.stat().st_size} bytes")
        lines.append("")
        lines.append("Approximate XMI counters:")
        lines.append(f"  action:Calls: {text.count('xsi:type=\"action:Calls\"')}")
        lines.append(f"  runtime_call labels: {text.count('runtime_call:')}")
        lines.append(f"  structure:Component: {text.count('xsi:type=\"structure:Component\"')}")
        lines.append(f"  structure:Subsystem: {text.count('xsi:type=\"structure:Subsystem\"')}")
        lines.append(f"  structure:StructureRelationship: {text.count('xsi:type=\"structure:StructureRelationship\"')}")
        lines.append(f"  extensionFamily: {text.count('extensionFamily')}")
        lines.append("")
        lines.append("Preview:")
        lines.append(text[:2000])
        return "\n".join(lines)

    def _summarize_text(self, path: Path) -> str:
        text = path.read_text(encoding="utf-8", errors="replace")
        return (
            f"Path: {path}\n"
            f"Size: {path.stat().st_size} bytes\n\n"
            f"Preview:\n{text[:4000]}"
        )

    def open_selected(self):
        item = self.list_widget.currentItem()

        if not item:
            return

        self._open_path(Path(item.data(Qt.ItemDataRole.UserRole)))

    def open_folder(self):
        if self.output_dir:
            self._open_path(self.output_dir)

    def copy_selected_path(self):
        item = self.list_widget.currentItem()

        if not item:
            return

        path = item.data(Qt.ItemDataRole.UserRole)
        self.window().clipboard().setText(path) if hasattr(self.window(), "clipboard") else None

        try:
            from PySide6.QtWidgets import QApplication
            QApplication.clipboard().setText(path)
        except Exception:
            pass

    def _open_path(self, path: Path):
        if sys.platform.startswith("linux"):
            subprocess.Popen(["xdg-open", str(path)])
        elif sys.platform == "darwin":
            subprocess.Popen(["open", str(path)])
        elif sys.platform.startswith("win"):
            subprocess.Popen(["cmd", "/c", "start", "", str(path)])

    def _short_type(self, value):
        if isinstance(value, list):
            return f"list[{len(value)}]"
        if isinstance(value, dict):
            return f"dict[{len(value)}]"
        return type(value).__name__

    def _artifact_sort_key(self, path: Path):
        order = {
            "python_model.json": 10,
            "python_model.runtime_enriched.combined.json": 20,
            "python_model.runtime_enriched.architecture.json": 30,
            "python_model.architecture.json": 31,
            "python_model.runtime_enriched.ai_architecture.json": 40,
            "python_model.ai_architecture.json": 41,
            "python_model.reviewed_architecture.json": 50,
            "model.reviewed.kdm.xmi": 60,
        }

        if path.name.startswith("runtime_trace."):
            return (15, path.name)

        return (order.get(path.name, 999), path.name)
