site_name: py2kdm
site_author: "Daniel San Martín"
site_description: KDM-based reverse engineering workbench for Python and Java projects
copyright: 'Author: <a href="https://www.danielsanmartin.cl/">Daniel San Martín</a>'
extra:
  author_url: "https://www.danielsanmartin.cl/"

theme:
  name: material

nav:
  - Home: index.md
  - 1. System purpose: 01-system-purpose.md
  - 2. Subprojects and standalone execution: 02-subprojects-cli.md
  - 3. Pipeline execution: 03-run-pipeline.md
  - 4. Project configuration files: 04-config-files.md
  - 5. Technical artifacts and KDM construction: 05-technical-artifacts-kdm.md
  - 6. Architecture agents: 06-architecture-agents.md
  - 7. Graphical User Interface: 07-gui.md
