class KDMValidationReport:
    """
    Collects validation errors, warnings and statistics produced by KDMValidator.

    The report is intentionally lightweight. It stores:
    - errors that should stop the generation pipeline;
    - warnings that indicate suspicious but non-fatal situations;
    - statistics about relevant KDM metaclasses found in the generated model.
    """

    def __init__(self):
        self.errors = []
        self.warnings = []
        self.infos = []
        self.stats = {}

    def add_error(self, message: str):
        """Adds a validation error."""
        self.errors.append(message)

    def add_warning(self, message: str):
        """Adds a validation warning."""
        self.warnings.append(message)

    def add_info(self, message: str):
        """Adds an informational validation note."""
        self.infos.append(message)

    def set_stat(self, key: str, value):
        """Stores a validation statistic."""
        self.stats[key] = value

    def has_errors(self):
        """Returns True when the report contains at least one error."""
        return len(self.errors) > 0

    def print_report(self):
        """Prints the validation report to standard output."""
        print("\n=== KDM VALIDATION REPORT ===")
        print(f"Errors: {len(self.errors)}")
        for error in self.errors:
            print(f"[ERROR] {error}")

        print(f"\nWarnings: {len(self.warnings)}")
        for warning in self.warnings:
            print(f"[WARNING] {warning}")

        if self.infos:
            print(f"\nInfos: {len(self.infos)}")
            for info in self.infos:
                print(f"[INFO] {info}")

        print("\nStats:")
        for key, value in self.stats.items():
            print(f"- {key}: {value}")


class KDMValidator:
    """
    Validates the generated KDM model.

    This validator performs generator-specific and KDM-oriented consistency
    checks over the PyEcore model produced by py2kdm.

    It validates:

    - inventory structure and source traceability;
    - relation targets for HasType, HasValue, Calls, Creates, Reads, Writes,
      Throws, Imports and Extends;
    - exception-flow semantics using TryUnit, CatchUnit, FinallyUnit,
      ExceptionFlow and ExitFlow;
    - return semantics using Reads or return_flow="void";
    - callable body structure using BlockUnit;
    - absence of obsolete temporary attributes;
    - absence of duplicate attributes, duplicate source regions and duplicate
      child actions.

    The validator is not intended to be a full KDM specification validator.
    Its purpose is to enforce the semantic conventions used by this generator.
    """

    OBSOLETE_ERROR_ATTRIBUTES = {
        # Removed in Step 4A / 4B
        "resolved",
        "target_id",
        "statement_type",
        "body_type",
        "control_type",
        "condition",
        "target",
        "iter",
        "exception",
        "value",
        "targets",

        # Old temporary/debug metadata
        "line",
        "line_start",
        "line_end",
        "path",
        "language",
        "assigned_value",
        "assigned_type",
        "resolved_type_qualified_name",
        "body_id",
        "callable_body_id",
        "source_call_name",
        "constructor_resolution",
        "constructor_target",
        "resolution",
        "unresolved_return_value",
        "unresolved_exception_type_target",
        "annotation",
        "function",
        "method",
        "class_name",
        "base_name",
        "source_class",

        # Generic ActionRelationship kind="catches"/"returns" should not appear.
        # KDM-specific relations should be used instead.
        "kind",
    }

    def __init__(self):
        """Initializes an empty validation report."""
        self.report = KDMValidationReport()

    def validate(self, segment):
        """
        Validates a generated KDM Segment.

        Parameters
        ----------
        segment:
            Root KDM Segment generated by the transformation pipeline.

        Returns
        -------
        KDMValidationReport
            Report containing errors, warnings and model statistics.
        """

        self.report = KDMValidationReport()

        all_elements = list(self._walk(segment))

        self._collect_stats(all_elements)

        self._validate_inventory(segment)
        self._validate_source_regions(all_elements)

        # Generator-specific consistency checks.
        self._validate_no_duplicate_attributes(all_elements)
        self._validate_no_duplicate_source_refs(all_elements)
        self._validate_no_duplicate_child_actions(all_elements)
        self._validate_callable_body_blocks(all_elements)

        # KDM semantic checks.
        self._validate_has_type(all_elements)
        self._validate_has_value(all_elements)
        self._validate_calls_and_creates(all_elements)
        self._validate_reads_writes(all_elements)
        self._validate_throws(all_elements)
        self._validate_returns(all_elements)
        self._validate_try_catch_finally_flows(all_elements)
        self._validate_imports_and_extends(all_elements)

        # Step 4 cleanup rule.
        self._validate_no_obsolete_attributes(all_elements)

        return self.report

    # ------------------------------------------------------------
    # Traversal
    # ------------------------------------------------------------

    def _walk(self, root):
        """
        Recursively walks containment references starting from a KDM element.

        Primitive values and non-containment references are ignored. This avoids
        traversing cross-references as if they were owned elements.
        """

        if root is None:
            return

        if not hasattr(root, "eClass"):
            return

        yield root

        for feature in root.eClass.eAllStructuralFeatures():
            if not getattr(feature, "containment", False):
                continue

            value = getattr(root, feature.name, None)

            if value is None:
                continue

            if hasattr(value, "__iter__") and not isinstance(value, (str, bytes)):
                for child in value:
                    if hasattr(child, "eClass"):
                        yield from self._walk(child)
            else:
                if hasattr(value, "eClass"):
                    yield from self._walk(value)

    def _has_feature(self, obj, feature_name: str):
        """Returns True if the PyEcore object supports a structural feature."""
        if obj is None or not hasattr(obj, "eClass"):
            return False

        return feature_name in [
            feature.name for feature in obj.eClass.eAllStructuralFeatures()
        ]

    def _is_instance_of(self, element, class_name: str):
        """
        Checks whether an element is an instance of a given EClass name or one
        of its supertypes.
        """

        if element is None or not hasattr(element, "eClass"):
            return False

        eclass = element.eClass

        if eclass.name == class_name:
            return True

        for super_type in eclass.eAllSuperTypes():
            if super_type.name == class_name:
                return True

        return False

    def _get_name(self, element):
        """Returns the name of an element when the name feature exists."""
        if self._has_feature(element, "name"):
            return getattr(element, "name", None)
        return None

    def _has_attribute(self, element, tag: str, value: str) -> bool:
        """Checks whether an element has an Attribute with a given tag/value."""
        if not self._has_feature(element, "attribute"):
            return False

        for attribute in element.attribute:
            if getattr(attribute, "tag", None) != tag:
                continue

            if getattr(attribute, "value", None) == str(value):
                return True

        return False

    def _has_attribute_tag(self, element, tag: str) -> bool:
        """Checks whether an element has an Attribute with the given tag."""
        if not self._has_feature(element, "attribute"):
            return False

        for attribute in element.attribute:
            if getattr(attribute, "tag", None) == tag:
                return True

        return False

    def _get_attribute_value(self, element, tag: str):
        """Returns the first value associated with an Attribute tag."""
        if not self._has_feature(element, "attribute"):
            return None

        for attribute in element.attribute:
            if getattr(attribute, "tag", None) == tag:
                return getattr(attribute, "value", None)

        return None

    # ------------------------------------------------------------
    # Stats
    # ------------------------------------------------------------

    def _collect_stats(self, all_elements):
        """Collects statistics for the most relevant KDM metaclasses."""

        counters = {}

        for element in all_elements:
            name = element.eClass.name
            counters[name] = counters.get(name, 0) + 1

        interesting = [
            "Segment",
            "InventoryModel",
            "SourceFile",
            "CodeModel",
            "CompilationUnit",
            "ClassUnit",
            "MethodUnit",
            "CallableUnit",
            "ParameterUnit",
            "StorableUnit",
            "ActionElement",
            "BlockUnit",
            "TryUnit",
            "CatchUnit",
            "FinallyUnit",
            "SourceRef",
            "SourceRegion",
            "Imports",
            "Extends",
            "Calls",
            "Creates",
            "Reads",
            "Writes",
            "Throws",
            "ExceptionFlow",
            "ExitFlow",
            "HasType",
            "HasValue",
            "Value",
            "Attribute",
        ]

        for key in interesting:
            self.report.set_stat(key, counters.get(key, 0))

    # ------------------------------------------------------------
    # Inventory and source traceability
    # ------------------------------------------------------------

    def _validate_inventory(self, segment):
        """
        Validates that the Segment contains an InventoryModel and SourceFile
        elements with paths.
        """

        inventory_models = []

        if self._has_feature(segment, "model"):
            for model in segment.model:
                if model.eClass.name == "InventoryModel":
                    inventory_models.append(model)

        if len(inventory_models) == 0:
            self.report.add_error("No InventoryModel found in Segment.")

        if len(inventory_models) > 1:
            self.report.add_warning(
                f"More than one InventoryModel found: {len(inventory_models)}."
            )

        source_files = []

        for inventory_model in inventory_models:
            if not self._has_feature(inventory_model, "inventoryElement"):
                self.report.add_error(
                    "InventoryModel does not have inventoryElement feature."
                )
                continue

            for item in inventory_model.inventoryElement:
                if item.eClass.name == "SourceFile":
                    source_files.append(item)

                    if not getattr(item, "path", None):
                        self.report.add_error(
                            f"SourceFile '{self._get_name(item)}' has no path."
                        )

        if len(source_files) == 0:
            self.report.add_error("No SourceFile found inside InventoryModel.")

    def _validate_source_regions(self, all_elements):
        """
        Validates SourceRegion elements.

        A SourceRegion must refer to a file or path, and its start line must
        not be greater than its end line.
        """

        source_regions = [
            element for element in all_elements if element.eClass.name == "SourceRegion"
        ]

        for region in source_regions:
            has_file = self._has_feature(region, "file") and getattr(region, "file", None)
            has_path = self._has_feature(region, "path") and getattr(region, "path", None)

            if not has_file and not has_path:
                self.report.add_error(
                    "SourceRegion has neither file reference nor path."
                )

            start_line = (
                getattr(region, "startLine", None)
                if self._has_feature(region, "startLine")
                else None
            )
            end_line = (
                getattr(region, "endLine", None)
                if self._has_feature(region, "endLine")
                else None
            )

            if start_line is not None and end_line is not None:
                if int(start_line) > int(end_line):
                    self.report.add_error(
                        f"SourceRegion has startLine > endLine: {start_line} > {end_line}."
                    )

    # ------------------------------------------------------------
    # Generator-specific consistency validations
    # ------------------------------------------------------------

    def _validate_no_duplicate_attributes(self, all_elements):
        """
        Ensures that a single KDM element does not contain duplicate
        Attribute entries with the same tag and value.
        """

        for element in all_elements:
            if not self._has_feature(element, "attribute"):
                continue

            seen = set()

            for attribute in element.attribute:
                key = (
                    getattr(attribute, "tag", None),
                    getattr(attribute, "value", None),
                )

                if key in seen:
                    self.report.add_error(
                        f"Duplicate Attribute on {element.eClass.name} "
                        f"'{self._get_name(element)}': tag='{key[0]}', value='{key[1]}'."
                    )

                seen.add(key)

    def _validate_no_duplicate_source_refs(self, all_elements):
        """
        Ensures that a single element does not contain duplicate source regions.
        """

        for element in all_elements:
            if not self._has_feature(element, "source"):
                continue

            seen = set()

            for source_ref in element.source:
                if not self._has_feature(source_ref, "region"):
                    continue

                for region in source_ref.region:
                    key = (
                        getattr(region, "path", None),
                        getattr(region, "startLine", None),
                        getattr(region, "endLine", None),
                        getattr(region, "startPosition", None),
                        getattr(region, "endPosition", None),
                    )

                    if key in seen:
                        self.report.add_error(
                            f"Duplicate SourceRegion on {element.eClass.name} "
                            f"'{self._get_name(element)}': {key}."
                        )

                    seen.add(key)

    def _validate_no_duplicate_child_actions(self, all_elements):
        """
        Ensures that the same parent does not contain duplicated executable
        child actions according to their class, name, kind and traceability ids.
        """

        for element in all_elements:
            if not self._has_feature(element, "codeElement"):
                continue

            seen = set()

            for child in element.codeElement:
                if not self._is_instance_of(child, "ActionElement"):
                    continue

                key = (
                    child.eClass.name,
                    self._get_name(child),
                    getattr(child, "kind", None)
                    if self._has_feature(child, "kind")
                    else None,
                    self._action_traceability_key(child),
                )

                if key in seen:
                    self.report.add_error(
                        f"Duplicate child action under {element.eClass.name} "
                        f"'{self._get_name(element)}': {key}."
                    )

                seen.add(key)

    def _action_traceability_key(self, action):
        """
        Returns a stable traceability key for duplicate-action validation.

        Source location is represented by source::SourceRegion and is the
        preferred discriminator for repeated calls. body_id/call_id are accepted
        only for backward compatibility with older generated models.
        """

        source_key = self._first_source_region_key(action)
        if source_key is not None:
            return f"source:{source_key}"

        body_id = self._get_attribute_value(action, "body_id")
        if body_id is not None:
            return f"body:{body_id}"

        call_id = self._get_attribute_value(action, "call_id")
        if call_id is not None:
            return f"call:{call_id}"

        return None

    def _first_source_region_key(self, element):
        if element is None or not self._has_feature(element, "source"):
            return None

        for source_ref in element.source:
            if not self._has_feature(source_ref, "region"):
                continue

            for region in source_ref.region:
                return (
                    getattr(region, "path", None),
                    getattr(region, "startLine", None),
                    getattr(region, "endLine", None),
                    getattr(region, "startPosition", None),
                    getattr(region, "endPosition", None),
                )

        return None

    def _validate_callable_body_blocks(self, all_elements):
        """
        Validates that executable actions inside MethodUnit / CallableUnit
        are grouped under a BlockUnit representing the callable body.

        Expected structure:

            MethodUnit / CallableUnit
              └── BlockUnit name="body"
                    ├── ActionElement
                    ├── TryUnit
                    ├── CatchUnit
                    ├── FinallyUnit
                    └── ...

        Direct ActionElement children under MethodUnit / CallableUnit are
        considered invalid, except for BlockUnit itself.
        """

        for element in all_elements:
            if element.eClass.name not in {"MethodUnit", "CallableUnit"}:
                continue

            if not self._has_feature(element, "codeElement"):
                continue

            body_blocks = []
            direct_action_children = []

            for child in element.codeElement:
                child_class = child.eClass.name

                if child_class == "BlockUnit":
                    if (
                        self._get_name(child) == "body"
                        or self._has_attribute(child, "role", "callable_body")
                    ):
                        body_blocks.append(child)
                    continue

                if self._is_instance_of(child, "ActionElement"):
                    direct_action_children.append(child)

            if len(body_blocks) > 1:
                self.report.add_error(
                    f"{element.eClass.name} '{self._get_name(element)}' "
                    f"has more than one callable body BlockUnit."
                )

            for action in direct_action_children:
                self.report.add_error(
                    f"{element.eClass.name} '{self._get_name(element)}' "
                    f"contains direct executable action "
                    f"{action.eClass.name} '{self._get_name(action)}'. "
                    "Executable body actions must be contained in a BlockUnit."
                )

            if body_blocks:
                self._validate_body_block(body_blocks[0], element)

    def _validate_body_block(self, block_unit, callable_element):
        """
        Validates a callable body BlockUnit.

        The block should be named body, have role="callable_body", support
        codeElement containment and contain at least one executable action.
        """

        if block_unit.eClass.name != "BlockUnit":
            self.report.add_error(
                f"Callable body of {self._get_name(callable_element)} "
                "is not a BlockUnit."
            )
            return

        if self._get_name(block_unit) != "body":
            self.report.add_warning(
                f"Callable body BlockUnit in "
                f"{callable_element.eClass.name} '{self._get_name(callable_element)}' "
                f"has name '{self._get_name(block_unit)}' instead of 'body'."
            )

        if not self._has_attribute(block_unit, "role", "callable_body"):
            self.report.add_warning(
                f"BlockUnit '{self._get_name(block_unit)}' under "
                f"{callable_element.eClass.name} '{self._get_name(callable_element)}' "
                "does not have role='callable_body'."
            )

        if not self._has_feature(block_unit, "codeElement"):
            self.report.add_error(
                f"BlockUnit '{self._get_name(block_unit)}' does not have codeElement."
            )
            return

        has_executable_child = False

        for child in block_unit.codeElement:
            if self._is_instance_of(child, "ActionElement"):
                has_executable_child = True
                break

        if not has_executable_child:
            self.report.add_warning(
                f"Callable body BlockUnit under "
                f"{callable_element.eClass.name} '{self._get_name(callable_element)}' "
                "does not contain executable ActionElement children."
            )

    # ------------------------------------------------------------
    # Type relations
    # ------------------------------------------------------------

    def _validate_has_type(self, all_elements):
        """Validates that every HasType relation points to a Datatype."""

        for element in all_elements:
            if element.eClass.name != "HasType":
                continue

            target = getattr(element, "to", None)

            if target is None:
                self.report.add_error("HasType relation without target.")
                continue

            if not self._is_instance_of(target, "Datatype"):
                self.report.add_error(
                    f"HasType target is not a Datatype: {target.eClass.name}."
                )

    # ------------------------------------------------------------
    # Value relations
    # ------------------------------------------------------------

    def _validate_has_value(self, all_elements):
        """
        Validates HasValue relation targets.

        In this generator, HasValue points to either a Value element or an
        ActionElement representing a computed value.
        """

        for element in all_elements:
            if element.eClass.name != "HasValue":
                continue

            target = getattr(element, "to", None)

            if target is None:
                self.report.add_error("HasValue relation without target.")
                continue

            valid_target = (
                target.eClass.name == "Value"
                or self._is_instance_of(target, "ActionElement")
            )

            if not valid_target:
                self.report.add_error(
                    f"HasValue target must be Value or ActionElement, got {target.eClass.name}."
                )

    # ------------------------------------------------------------
    # Call/create relations
    # ------------------------------------------------------------

    def _validate_calls_and_creates(self, all_elements):
        """
        Validates Calls and Creates relations and warns when constructor calls
        do not have a Creates relation.
        """

        for element in all_elements:
            if element.eClass.name not in {"Calls", "Creates"}:
                continue

            target = getattr(element, "to", None)

            if target is None:
                self.report.add_error(f"{element.eClass.name} relation without target.")

        for element in all_elements:
            if element.eClass.name != "ActionElement":
                continue

            kind = (
                getattr(element, "kind", None)
                if self._has_feature(element, "kind")
                else None
            )

            if kind == "constructor_call":
                has_creates = self._has_action_relation(element, "Creates")

                if not has_creates:
                    self.report.add_warning(
                        f"Constructor ActionElement '{self._get_name(element)}' has no Creates relation."
                    )

    # ------------------------------------------------------------
    # Reads/Writes
    # ------------------------------------------------------------

    def _validate_reads_writes(self, all_elements):
        """
        Validates Reads and Writes relations.

        In py2kdm, Reads and Writes targets must be StorableUnit elements.
        """

        for element in all_elements:
            if element.eClass.name not in {"Reads", "Writes"}:
                continue

            target = getattr(element, "to", None)

            if target is None:
                self.report.add_error(f"{element.eClass.name} relation without target.")
                continue

            if not self._is_instance_of(target, "StorableUnit"):
                self.report.add_error(
                    f"{element.eClass.name} target must be StorableUnit, got {target.eClass.name}."
                )

    # ------------------------------------------------------------
    # Throws / raise
    # ------------------------------------------------------------

    def _validate_throws(self, all_elements):
        """
        Validates Throws relations and raise ActionElement semantics.

        Throws must point to a StorableUnit representing the thrown exception
        object. A raise ActionElement must either have Throws or be marked as
        exception_flow="rethrow".
        """

        for element in all_elements:
            if element.eClass.name == "Throws":
                target = getattr(element, "to", None)

                if target is None:
                    self.report.add_error("Throws relation without target.")
                    continue

                if not self._is_instance_of(target, "StorableUnit"):
                    self.report.add_error(
                        f"Throws target must be StorableUnit, got {target.eClass.name}."
                    )

        for element in all_elements:
            if element.eClass.name != "ActionElement":
                continue

            kind = (
                getattr(element, "kind", None)
                if self._has_feature(element, "kind")
                else None
            )

            if kind != "raise":
                continue

            has_throws = self._has_action_relation(element, "Throws")
            has_rethrow = self._has_attribute(element, "exception_flow", "rethrow")

            if not has_throws and not has_rethrow:
                self.report.add_error(
                    "Raise ActionElement must have Throws or exception_flow='rethrow'."
                )

    # ------------------------------------------------------------
    # Return
    # ------------------------------------------------------------

    def _validate_returns(self, all_elements):
        """
        Validates return ActionElement semantics.

        A return action must have one of the following:
        - a Reads relation to the returned value;
        - return_flow="void" for bare returns.
        """

        for element in all_elements:
            if element.eClass.name != "ActionElement":
                continue

            kind = (
                getattr(element, "kind", None)
                if self._has_feature(element, "kind")
                else None
            )

            if kind != "return":
                continue

            has_reads = self._has_action_relation(element, "Reads")
            has_void = self._has_attribute(element, "return_flow", "void")
            if not has_reads and not has_void:
                self.report.add_error(
                    "Return ActionElement must have Reads "
                    "or return_flow='void'."
                )

    # ------------------------------------------------------------
    # Try / Catch / Finally
    # ------------------------------------------------------------

    def _validate_try_catch_finally_flows(self, all_elements):
        """
        Validates exception-control structures.

        - A CatchUnit contained in a TryUnit must be targeted by ExceptionFlow.
        - A FinallyUnit contained in a TryUnit must be targeted by ExitFlow.
        - ExceptionFlow targets must be CatchUnit.
        - ExitFlow targets must be FinallyUnit.
        """

        for element in all_elements:
            if element.eClass.name != "TryUnit":
                continue

            catch_units = []
            finally_units = []

            if self._has_feature(element, "codeElement"):
                for child in element.codeElement:
                    if child.eClass.name == "CatchUnit":
                        catch_units.append(child)

                    if child.eClass.name == "FinallyUnit":
                        finally_units.append(child)

            exception_flow_targets = self._get_action_relation_targets(
                element,
                "ExceptionFlow",
            )

            exit_flow_targets = self._get_action_relation_targets(
                element,
                "ExitFlow",
            )

            for catch_unit in catch_units:
                if catch_unit not in exception_flow_targets:
                    self.report.add_error(
                        "CatchUnit contained in TryUnit must be targeted by ExceptionFlow."
                    )

            for finally_unit in finally_units:
                if finally_unit not in exit_flow_targets:
                    self.report.add_error(
                        "FinallyUnit contained in TryUnit must be targeted by ExitFlow."
                    )

        for element in all_elements:
            if element.eClass.name == "ExceptionFlow":
                target = getattr(element, "to", None)

                if target is None:
                    self.report.add_error("ExceptionFlow relation without target.")
                elif target.eClass.name != "CatchUnit":
                    self.report.add_error(
                        f"ExceptionFlow target must be CatchUnit, got {target.eClass.name}."
                    )

            if element.eClass.name == "ExitFlow":
                target = getattr(element, "to", None)

                if target is None:
                    self.report.add_error("ExitFlow relation without target.")
                elif target.eClass.name != "FinallyUnit":
                    self.report.add_error(
                        f"ExitFlow target must be FinallyUnit, got {target.eClass.name}."
                    )

    # ------------------------------------------------------------
    # Imports / Extends
    # ------------------------------------------------------------

    def _validate_imports_and_extends(self, all_elements):
        """Validates that Imports and Extends relations have targets."""

        for element in all_elements:
            if element.eClass.name not in {"Imports", "Extends"}:
                continue

            target = getattr(element, "to", None)

            if target is None:
                self.report.add_error(f"{element.eClass.name} relation without target.")

    # ------------------------------------------------------------
    # Obsolete attributes
    # ------------------------------------------------------------

    def _validate_no_obsolete_attributes(self, all_elements):
        """
        Ensures that temporary attributes removed from the final mapping do not
        reappear in the generated KDM model.
        """

        for element in all_elements:
            if element.eClass.name != "Attribute":
                continue

            tag = getattr(element, "tag", None)
            value = getattr(element, "value", None)

            if tag in self.OBSOLETE_ERROR_ATTRIBUTES:
                self.report.add_error(
                    f"Obsolete Attribute found: tag='{tag}', value='{value}'."
                )

    # ------------------------------------------------------------
    # Generic relation helpers
    # ------------------------------------------------------------

    def _has_action_relation(self, element, relation_type: str) -> bool:
        """Checks whether an element has an action relation of a given type."""
        if not self._has_feature(element, "actionRelation"):
            return False

        for relation in element.actionRelation:
            if relation.eClass.name == relation_type:
                return True

        return False

    def _get_action_relation_targets(self, element, relation_type: str):
        """Returns all targets of action relations of a given type."""
        targets = set()

        if not self._has_feature(element, "actionRelation"):
            return targets

        for relation in element.actionRelation:
            if relation.eClass.name != relation_type:
                continue

            target = getattr(relation, "to", None)

            if target is not None:
                targets.add(target)

        return targets
